export const TYPES = {
  USERS_FETCHED: 'USERS_FETCHED',
  USERS_FETCHED_ASYNC: 'USERS_FETCHED_ASYNC',
  USER_FETCHED: 'USER_FETCHED',
  USER_FETCHED_ASYNC: 'USER_FETCHED_ASYNC',
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_ASYNC: 'CREATE_USER_ASYNC',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_ASYNC: 'DELETE_USER_ASYNC',
  ERROR: 'ERROR',
};